<?php

namespace App\Http\Controllers;

use App\Http\Requests\FinanceIndexRequest;
use App\Http\Requests\StoreExpenseRequest;
use App\Http\Requests\StoreIncomeRequest;
use App\Models\Expense;
use App\Models\Income;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\View\View;

class FinanceController extends Controller
{
    /**
     * Financial summary (incomes, expenses, profit) for a date range.
     */
    public function index(FinanceIndexRequest $request): View
    {
        $from = $this->fromDate($request);
        $to = $this->toDate($request);

        $totalIncome = round((float) Income::whereDate('income_date', '>=', $from)
            ->whereDate('income_date', '<=', $to)
            ->sum('amount'), 2);
        $totalExpense = round((float) Expense::whereDate('expense_date', '>=', $from)
            ->whereDate('expense_date', '<=', $to)
            ->sum('amount'), 2);
        $profit = round($totalIncome - $totalExpense, 2);

        $incomes = Income::query()
            ->with('user')
            ->whereDate('income_date', '>=', $from)
            ->whereDate('income_date', '<=', $to)
            ->orderByDesc('income_date')
            ->orderByDesc('id')
            ->paginate(10, ['*'], 'incomes_page')
            ->withQueryString();

        $expenses = Expense::query()
            ->with('user')
            ->whereDate('expense_date', '>=', $from)
            ->whereDate('expense_date', '<=', $to)
            ->orderByDesc('expense_date')
            ->orderByDesc('id')
            ->paginate(10, ['*'], 'expenses_page')
            ->withQueryString();

        return view('finances.index', compact(
            'from',
            'to',
            'totalIncome',
            'totalExpense',
            'profit',
            'incomes',
            'expenses',
        ));
    }

    /**
     * Register a manual income (type "other").
     */
    public function storeIncome(StoreIncomeRequest $request): RedirectResponse
    {
        Income::create([
            'type' => 'other',
            'description' => $request->validated('description'),
            'amount' => $request->validated('amount'),
            'income_date' => $request->validated('income_date'),
            'user_id' => auth()->id(),
        ]);

        return back()->with('success', 'Ingreso registrado correctamente.');
    }

    /**
     * Register an expense.
     */
    public function storeExpense(StoreExpenseRequest $request): RedirectResponse
    {
        Expense::create([
            'category' => $request->validated('category'),
            'description' => $request->validated('description'),
            'amount' => $request->validated('amount'),
            'expense_date' => $request->validated('expense_date'),
            'user_id' => auth()->id(),
        ]);

        return back()->with('success', 'Egreso registrado correctamente.');
    }

    /**
     * Delete a manual income. Incomes generated by sales cannot be deleted here.
     */
    public function destroyIncome(Income $income): RedirectResponse
    {
        if ($income->type !== 'other' || $income->reference_type !== null) {
            return back()->with('error', 'Solo se pueden eliminar ingresos manuales.');
        }

        $income->delete();

        return back()->with('success', 'Ingreso eliminado correctamente.');
    }

    /**
     * Delete an expense.
     */
    public function destroyExpense(Expense $expense): RedirectResponse
    {
        $expense->delete();

        return back()->with('success', 'Egreso eliminado correctamente.');
    }

    private function fromDate(Request $request): string
    {
        return $request->filled('date_from')
            ? Carbon::parse($request->input('date_from'))->startOfDay()->toDateString()
            : now()->startOfMonth()->toDateString();
    }

    private function toDate(Request $request): string
    {
        return $request->filled('date_to')
            ? Carbon::parse($request->input('date_to'))->endOfDay()->toDateString()
            : now()->endOfMonth()->toDateString();
    }
}
